export default [
    {
        id:'b1',
        title:'Curb Small Polished Silver Hoops',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/Asym-Bracelet-primary_dd376018-5833-489c-bd37-7dccf65bf22f_400x.jpg?v=1663158609',
    },
    {
        id:'b2',
        title:'Curb Large Silver Hoops w. Zirconia',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/Akva2001new_400x.jpg?v=1665047191',
    },
    {
        id:'b3',
        title:'Galene Silver Earrings',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/Asym-Bracelet_400x.jpg?v=1663158606',
    },
    {
        id:'b4',
        title:'Curb Medium Gold Plated Hoops',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/ASYM_4_e1cd5377-370f-430e-9ff7-4ca7933c7f9d_800x800.jpg?v=1663158803',
    },
    {
        id:'b5',
        title:'UMARI Gold Plated Pendant',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/ELVA-white-gold_800x.jpg?v=1662973655',
    },
    {
        id:'b6',
        title:'IX Square Pendant Gold Plated',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/Maia-wg_800x.jpg?v=1662973667',
    },
    {
        id:'b7',
        title:'Gem Candy 18K Gold Plated Earring-Pendant w. Topaz',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/MIRANDA-gold_800x.jpg?v=1662973699',
    },
    {
        id:'b8',
        title:'The breath Silver Pendant',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/KHA1_F1030_400x.jpg?v=1662469793',
    },
    {
        id:'b9',
        title:'IX Cent Earring Silver',
        text:'Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.Who can resist the alluring power of jewellery? It transforms not only how you look, but also how you feel. More than just a fashion accessory, choosing and wearing designer jewellery is a deeply personal connection with the inspiration of each piece. Jewellery reflects the culture and values of the time. Today, jewellery design involves a blend of ancient goldsmithing and gemstone crafts along with technological tools to create delicate and intricate designs. Jewellery designers use beautiful jewels and precious metals to make amazing innovative jewellery in the form of wearable art.',
        img:'https://cdn.shopify.com/s/files/1/0555/3402/6935/products/236-SSWH_182fb4e5-642b-4866-989b-3189ef267b12_400x.jpg?v=1662559550',
    },
]